name: deploy frontend
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "portal/**"
env:
  NODE_VERSION: "18.x"
  AZURE_WEBAPP_NAME: ApraxiaFrontEnd
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Use node.js ${{env.NODE_VERSION}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: npm install and build
        run: |
          cd portal/
          yarn install
          yarn run build

      - name: uploading frontend artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: frontend-app
          path: "portal/dist"
          if-no-files-found: error
          retention-days: 30
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: azure/login@v1.1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: downloading artifact
        uses: actions/download-artifact@v2

      - name: deploy to azure web app
        id: deploy-to-web-app
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{env.AZURE_WEBAPP_NAME}}
          package: ./frontend-app
